### ISSUE TITLE
Plugin error during okta_template_email creation

### ISSUE THREAD

**Issue by naveen-vijay** [okta/terraform-provider-okta#1064]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.1.8
provider registry.terraform.io/okta/okta v3.23.0

### Affected Resource(s)

- okta_template_email

### Terraform Configuration Files

```hcl

locals {
  email_template_location = "./email_templates/email-"
  email_template_lookup_table = [
    {
      type     = "email.authenticatorEnrollment"
      filename = "MFAEnrolled.html"
    },
    {
      type     = "email.authenticatorReset"
      filename = "MFAReset.html"
    }
  ]
}

resource "okta_template_email" "EN" {
  type = local.email_template_lookup_table[count.index].type

  translations {
    language = "en"
    subject  = local.email_template_lookup_table[count.index].type
    template = file("${local.email_template_location}EN/${local.email_template_lookup_table[count.index].filename}")
  }

  count = length(local.email_template_lookup_table)
}

resource "okta_template_email" "PT" {
  type = local.email_template_lookup_table[count.index].type

  translations {
    language = "es"
    subject  = local.email_template_lookup_table[count.index].type
    template = file("${local.email_template_location}PT/${local.email_template_lookup_table[count.index].filename}")
  }

  count = length(local.email_template_lookup_table)
}

```

#### MFAEnrolled.html

```html

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<div style="background-color: ${brand.theme.secondaryColor}; margin: 0">
    <table style="font-family: 'Proxima Nova', 'Century Gothic', 'Arial', 'Verdana', sans-serif; font-size: 14px; color: #5e5e5e; width:98%; max-width: 600px; float: none; margin: 0 auto" border="0" cellpadding="0" cellspacing="0" valign="top" align="left">
    <tbody>
        <tr align="middle"><td style="padding-top: 30px; padding-bottom: 32px"><img src="${brand.theme.logo}" height="37"/></td></tr>
        <tr bgcolor="#ffffff"><td>
            <table bgcolor="#ffffff" style="width: 100%; line-height: 20px; padding: 32px; border: 1px solid; border-color: #f0f0f0" cellpadding="0">
            <tbody>
                <tr>
                    <td style="padding-top: 24px">
                        Hallo $!{StringTool.escapeHtml($!{user.profile.firstName})},
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px">
                        F&uuml;r Ihr Konto ${user.profile.login} wurde eine Sicherheitsmethode registriert.
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px; font-size: 18px; font-weight: 600; color: #5e5e5e; line-height: 24px">
                        Details
                    </td>
                </tr>
                <tr>
                    <td style="line-height: 24px">
                        ${request.factor}
                        <br/>
                        ${request.date}
                        <br/>
                        ${request.location}
                        <br/>
                        Ausgef&uuml;hrt von: ${request.performedBySubject}
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px; font-size: 18px; font-weight: 600; color: #5e5e5e; line-height: 24px">
                        Sie k&ouml;nnen sich nicht an diesen Vorgang erinnern?
                    </td>
                </tr>
                <tr>
                    <td>
                        Ihr Konto wurde m&ouml;glicherweise manipuliert; wir empfehlen, die verd&auml;chtigen Aktivit&auml;t an Ihr Unternehmen zu melden.
                    </td>
                </tr>
                <tr>
                    <td align="center" style="height: 32px;padding-top: 24px">
                        <a href="${baseUrl}/enduser/report-suspicious-activity?i=${request.reportSuspiciousActivityToken}" id="report-suspicious-activity" style="text-decoration: none">
                            <span style="padding: 9px 32px 7px 31px;border: 1px solid;text-align: center;cursor: pointer;color: rgb(255,255,255);border-radius: 3px;background-color: ${brand.theme.primaryColor};border-color: ${brand.theme.primaryColor};box-shadow: 0 1px 0 ${brand.theme.primaryColor}">Verd&auml;chtige Aktivit&auml;t melden</span>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px">
                        Die Sicherheit Ihres Kontos ist uns sehr wichtig und wir m&ouml;chten sicherstellen, dass Sie informiert werden, wenn wichtige Vorg&auml;nge geschehen.
                    </td>
                </tr>
            </tbody></table>
        </td></tr>
        <tr>
            <td style="font-size: 12px; padding: 16px 0 30px 50px; color: #999">
                Dies Nachricht wurde am ${request.date} um ${request.time} automatisch von <a href="http://www.okta.com" style="color: rgb(97,97,97)">Okta</a> generiert. Antworten werden nicht gelesen oder beantwortet.
            </td>
        </tr>
    </tbody></table>
</div>
</body>
</html>




```

#### MFAReset.html

```html

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
<div style="background-color: ${brand.theme.secondaryColor}; margin: 0">
    <table style="font-family: 'Proxima Nova', 'Century Gothic', 'Arial', 'Verdana', sans-serif; font-size: 14px; color: #5e5e5e; width:98%; max-width: 600px; float: none; margin: 0 auto" border="0" cellpadding="0" cellspacing="0" valign="top" align="left">
    <tbody>
        <tr align="middle"><td style="padding-top: 30px; padding-bottom: 32px"><img src="${brand.theme.logo}" height="37"/></td></tr>
        <tr bgcolor="#ffffff"><td>
            <table bgcolor="#ffffff" style="width: 100%; line-height: 20px; padding: 32px; border: 1px solid; border-color: #f0f0f0" cellpadding="0">
            <tbody>
                <tr>
                    <td style="padding-top: 24px">
                        Hallo $!{StringTool.escapeHtml($!{user.profile.firstName})},
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px">
                        Mindestens eine Sicherheitsmethode wurde f&uuml;r Ihr Konto ${user.profile.login} zur&uuml;ckgesetzt.
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px; font-size: 18px; font-weight: 600; color: #5e5e5e; line-height: 24px">
                        Details
                    </td>
                </tr>
                <tr>
                    <td style="line-height: 24px">
                        ${request.factors}
                        <br/>
                        ${request.date}
                        <br/>
                        ${request.location}
                        <br/>
                        Ausgef&uuml;hrt von: ${request.performedBySubject}
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px; font-size: 18px; font-weight: 600; color: #5e5e5e; line-height: 24px">
                        Sie k&ouml;nnen sich nicht an diesen Vorgang erinnern?
                    </td>
                </tr>
                <tr>
                    <td>
                        Ihr Konto wurde m&ouml;glicherweise manipuliert; wir empfehlen, die verd&auml;chtigen Aktivit&auml;t an Ihr Unternehmen zu melden.
                    </td>
                </tr>
                <tr>
                    <td align="center" style="height: 32px;padding-top: 24px">
                        <a href="${baseUrl}/enduser/report-suspicious-activity?i=${request.reportSuspiciousActivityToken}" id="report-suspicious-activity" style="text-decoration: none">
                            <span style="padding: 9px 32px 7px 31px;border: 1px solid;text-align: center;cursor: pointer;color: rgb(255,255,255);border-radius: 3px;background-color: ${brand.theme.primaryColor};border-color: ${brand.theme.primaryColor};box-shadow: 0 1px 0 ${brand.theme.primaryColor}">Verd&auml;chtige Aktivit&auml;t melden</span>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="padding-top: 24px">
                        Die Sicherheit Ihres Kontos ist uns sehr wichtig und wir m&ouml;chten sicherstellen, dass Sie informiert werden, wenn wichtige Vorg&auml;nge geschehen.
                    </td>
                </tr>
            </tbody></table>
        </td></tr>
        <tr>
            <td style="font-size: 12px; padding: 16px 0 30px 50px; color: #999">
                Dies Nachricht wurde am ${request.date} um ${request.time} automatisch von <a href="http://www.okta.com" style="color: rgb(97,97,97)">Okta</a> generiert. Antworten werden nicht gelesen oder beantwortet.
            </td>
        </tr>
    </tbody></table>
</div>
</body>
</html>

```

### Debug Output

```hcl

okta_template_email.EN[1]: Creating...
okta_template_email.EN[0]: Creating...
okta_template_email.PT[0]: Creating...
okta_template_email.PT[1]: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with okta_template_email.EN[0],
│   on main.tf line 15, in resource "okta_template_email" "EN":
│   15: resource "okta_template_email" "EN" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with okta_template_email.EN[1],
│   on main.tf line 15, in resource "okta_template_email" "EN":
│   15: resource "okta_template_email" "EN" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with okta_template_email.PT[1],
│   on main.tf line 27, in resource "okta_template_email" "PT":
│   27: resource "okta_template_email" "PT" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with okta_template_email.PT[0],
│   on main.tf line 27, in resource "okta_template_email" "PT":
│   27: resource "okta_template_email" "PT" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-okta_v3.23.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1048b1c54]

goroutine 22 [running]:
github.com/okta/terraform-provider-okta/okta.buildEmailTemplate(0x140001c4b80)
        github.com/okta/terraform-provider-okta/okta/resource_okta_template_email.go:173 +0x1e4
github.com/okta/terraform-provider-okta/okta.resourceTemplateEmailCreate({0x104bf6b08, 0x140003ba240}, 0x140001c4b80, {0x104ac2ae0, 0x14000453ee0})
        github.com/okta/terraform-provider-okta/okta/resource_okta_template_email.go:110 +0x30
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x140004717a0, {0x104bf6b40, 0x1400089de90}, 0x140001c4b80, {0x104ac2ae0, 0x14000453ee0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:708 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140004717a0, {0x104bf6b40, 0x1400089de90}, 0x1400077c1a0, 0x140001c4a00, {0x104ac2ae0, 0x14000453ee0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/resource.go:838 +0xa4c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000435fc8, {0x104bf6a98, 0x1400004ad80}, 0x140002cacd0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/helper/schema/grpc_provider.go:1021 +0xedc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000327e00, {0x104bf6b40, 0x1400089d800}, 0x140005acf50)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x104b995e0, 0x14000327e00}, {0x104bf6b40, 0x1400089d800}, 0x1400070d080, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002aca80, {0x104c052d0, 0x14000600820}, 0x140001f79e0, 0x14000551770, 0x10517d8a0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xc5c
google.golang.org/grpc.(*Server).handleStream(0x140002aca80, {0x104c052d0, 0x14000600820}, 0x140001f79e0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400061a480, 0x140002aca80, {0x104c052d0, 0x14000600820}, 0x140001f79e0)
        google.golang.org/grpc@v1.45.0/server.go:921 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x1f0

Error: The terraform-provider-okta_v3.23.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


```

### Expected Behavior

The email templates for EN and PT languages be created. 

### Actual Behavior

Plugin crash error

### Steps to Reproduce

1. `terraform apply`

**Comment by monde** [comment]
Thanks @naveen-vijay . I'll be looking into this.

**Comment by monde** [comment]
@naveen-vijay `okta_template_email` deprecated now. Please switch over to the `okta_email_customization` resource.  https://registry.terraform.io/providers/okta/okta/latest/docs/resources/email_customization
