### ISSUE TITLE
failed import "catch_all_rule"

### ISSUE THREAD

**Issue by exitcode0** [okta/terraform-provider-okta#1354]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/okta/okta v3.38.0
```

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.3.4"
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.38.0"
    }
  }
}

provider "okta" {
  org_name         = var.OKTA_ORG_NAME
  base_url         = var.OKTA_BASE_URL
  api_token        = var.OKTA_API_TOKEN
  max_api_capacity = 10 # percent of instance wide rate limit per endpoint
}

variable "OKTA_ORG_NAME" {}
variable "OKTA_BASE_URL" {}
variable "OKTA_API_TOKEN" { sensitive = true }

resource "okta_policy_rule_signon" "catch_all_rule" {
}
```

### Panic Output

```
okta_policy_rule_signon.catch_all_rule: Importing from ID "<APP_ID/<RULE_ID>"...
okta_policy_rule_signon.catch_all_rule: Import prepared!
  Prepared okta_policy_rule_signon for import
okta_policy_rule_signon.catch_all_rule: Refreshing state... [id=<RULE_ID>]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-okta_v3.38.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102db4fb0]

goroutine 28 [running]:
github.com/okta/terraform-provider-okta/okta.resourcePolicySignOnRuleRead({0x10311ee48, 0x14000115500}, 0x1400033ea00, {0x102fe5d00, 0x140001fb440})
        github.com/okta/terraform-provider-okta/okta/resource_okta_policy_rule_sign_on.go:172 +0x70
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400050f880, {0x10311ee80, 0x14000308de0}, 0x1400033ea00, {0x102fe5d00, 0x140001fb440})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:724 +0x118
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400050f880, {0x10311ee80, 0x14000308de0}, 0x140002391e0, {0x102fe5d00, 0x140001fb440})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/resource.go:1015 +0x548
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000586108, {0x10311ee80, 0x14000308c60}, 0x1400028e340)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.19.0/helper/schema/grpc_provider.go:613 +0x658
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140004ba0a0, {0x10311ee80, 0x14000308420}, 0x14000114ba0)
        github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/tf5server/server.go:747 +0x474
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1030bfe00, 0x140004ba0a0}, {0x10311ee80, 0x14000308420}, 0x140006fa000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.12.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400013aa80, {0x10312de00, 0x14000292820}, 0x1400047c000, 0x1400057fdd0, 0x1036c9f70, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb50
google.golang.org/grpc.(*Server).handleStream(0x1400013aa80, {0x10312de00, 0x14000292820}, 0x1400047c000, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400029e570, 0x1400013aa80, {0x10312de00, 0x14000292820}, 0x1400047c000)
        google.golang.org/grpc@v1.48.0/server.go:932 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x1f0

Error: The terraform-provider-okta_v3.38.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

successful import after running 
```terraform import \
-var OKTA_ORG_NAME=domain \
-var OKTA_BASE_URL=okta.com \
-var OKTA_API_TOKEN=$OKTA_API_TOKEN \
okta_policy_rule_signon.catch_all_rule <APP_ID>/<RULE_ID>
```

### Actual Behavior

Panic output included above

### Steps to Reproduce

1. `terraform apply`

### References

- #0000

**Comment by monde** [comment]
Thanks @exitcode0 . We are looking to dedicate a future sprint to import bugs.
https://oktainc.atlassian.net/browse/OKTA-550870

**Comment by antonmos** [comment]
Please keep open

**Comment by antonmos** [comment]
Please keep open
