### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b1934c]

### ISSUE THREAD

**Issue by JBorregoE** [okta/terraform-provider-okta#1601]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_policy_rule_signon

### Terraform Configuration Files

```hcl
resource okta_policy_signon policy {
    name        = "Policy_name"
    description =  "Policy description"
}

resource okta_policy_rule_signon rule {
   policy_id = okta_policy_signon.policy.id
   name      = "ruleName"
}
```

### Debug Output

https://gist.github.com/JBorregoE/f74f05ec40f7c7f9eb34013c84384efb

### Panic Output

2023-06-22T10:58:30.720+0200 [DEBUG] [aws-sdk-go] {}

Stack trace from the terraform-provider-okta_v3.46.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100b1934c]

goroutine 89 [running]:
github.com/okta/terraform-provider-okta/okta.resourcePolicySignOnRuleRead({0x100eb6e08?, 0x14000acf9b0?}, 0x0?, {0x100d817a0?, 0x14000301320?})
        github.com/okta/terraform-provider-okta/okta/resource_okta_policy_rule_sign_on.go:172 +0x4c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x140004a7880, {0x100eb6e40, 0x14000aced20}, 0xd?, {0x100d817a0, 0x14000301320})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140004a7880, {0x100eb6e40, 0x14000aced20}, 0x14000509ad0, {0x100d817a0, 0x14000301320})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140007160c0, {0x100eb6e40?, 0x14000acec00?}, 0x140003544c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400072c000, {0x100eb6e40?, 0x14000ace240?}, 0x1400012a420)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x100e70c00?, 0x1400072c000}, {0x100eb6e40, 0x14000ace240}, 0x1400057e0e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002041e0, {0x100ebad78, 0x14000402d00}, 0x1400090e240, 0x14000712300, 0x1014425d0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xbac
google.golang.org/grpc.(*Server).handleStream(0x140002041e0, {0x100ebad78, 0x14000402d00}, 0x1400090e240, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28c

Error: The terraform-provider-okta_v3.46.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2023-06-22T10:58:30.720+0200 [DEBUG] provider: plugin exited
ERRO[0011] Terraform invocation failed in /Users/my-name/Documents/Git/sso-and-directory-management/sandbox 
ERRO[0011] 1 error occurred:
        * exit status 1

### Expected Behavior

The import should end up successfully.

#### Can this be done in the Admin UI?

I don't know

#### Can this be done in the actual API call?

I don't know

### Actual Behavior

During the import of the resource the provider crashed.

### Steps to Reproduce

1. `terraform import okta_policy_rule_signon.rule <policy id>/<rule id>`

### Important Factoids

My Okta rule has the Device Assurance policies configured.

### References

https://registry.terraform.io/providers/okta/okta/latest/docs/resources/app_signon_policy_rule

- #0000

**Comment by JBorregoE** [comment]
Forget about this. I used the wrong resource. The right one was `okta_app_signon_policy_rule`.

I realized is that Device Assurance policies are not available yet in the provider. Furthermore, each time I apply a change in this rule they get overwritten in the GUI. I will look for a workaround, but that is a different topic.
