### ISSUE TITLE
okta_idp_saml import Runtime Error

### ISSUE THREAD

**Issue by nshe-dtaliaferro** [okta/terraform-provider-okta#2096]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/okta/okta v4.11.0
```

### Affected Resource(s)

- okta_idp_saml

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "okta_idp_saml" "samlidp" {
  name = "saml-idp"
}

> terraform import okta_idp_saml.samlidp "<SAML-IDP-ID>"
```

### Debug Output

Can provide via encrypted file if needed.

### Panic Output

```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-okta_v4.11.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1bbc538]

goroutine 51 [running]:
github.com/okta/terraform-provider-okta/okta.resourceIdpSamlRead({0x24349a0, 0xc0000e8e70}, 0xc000281780, {0x1f55b40?, 0xc00055db00?})
        github.com/okta/terraform-provider-okta/okta/resource_okta_idp_saml.go:149 +0x278
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000352b60, {0x24348f8, 0xc0003115f0}, 0xd?, {0x1f55b40, 0xc00055db00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:795 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000352b60, {0x24348f8, 0xc0003115f0}, 0xc0003b1450, {0x1f55b40, 0xc00055db00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00030cd38, {0x24348f8?, 0xc000311500?}, 0xc000051600)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:661 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x2434930?, {0x24348f8?, 0xc0003107b0?}, 0xc000051600)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00026c140, {0x24348f8?, 0xc0005c17d0?}, 0xc000692480)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:775 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x20a7bc0?, 0xc00026c140}, {0x24348f8, 0xc0005c17d0}, 0xc000281200, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00016ee00, {0x24348f8, 0xc0005c1740}, {0x243b0d8, 0xc00017e180}, 0xc000307e60, 0xc0003b5d70, 0x335b6e8, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc00016ee00, {0x243b0d8, 0xc00017e180}, 0xc000307e60)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 39
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-okta_v4.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

The API response does not include an "acs" key under Protocol.Endpoints, which is what I think the import is looking for

### Steps to Reproduce

1. ` terraform import okta_idp_saml.samlidp "<SAML-IDP-ID>"`

**Comment by arvindkrishnakumar-okta** [comment]
Internal JIRA for reference: https://oktainc.atlassian.net/browse/OKTA-809800

**Comment by dhiwakar-okta** [comment]
@nshe-dtaliaferro please let us know if the issue is present in v6.6.1 of the Terraform Provider.

**Comment by dhiwakar-okta** [comment]
Closing this issue due to a lack of response.

**Comment by nshe-dtaliaferro** [comment]
Apologies for the delay, I haven't tested fully but an initial import seems to succeed now.
