### ISSUE TITLE
4.12.0 - Plugin Crash when running Plan

### ISSUE THREAD

**Issue by delize** [okta/terraform-provider-okta#2150]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.9.8 via Hashicorp CI / CD

### Affected Resource(s)

Not Applicable

### Terraform Configuration Files

I am unable to do so due to company regulations. Happy to share this privately, but unable to do so publicly.

Please see the Okta Support Case for the configuration and DEBUG output.

EDIT: Was able to get approval to share the pieces of the code that caused the stack trace:
```
# import {
#   to = okta_policy_rule_password.default_password_rule
#   id = "POLICY_ID/RULE_ID1"
# }

# import {
#   to = okta_policy_rule_password.custom_password_rule
#   id = "POLICY_ID/RULE_ID2"
# }

# # Define Password Policy Rule: Custom Rule
# resource "okta_policy_rule_password" "custom_password_rule" {
#   name               = "Custom Password Policy Rule" # Update the name as per your environment
#   policy_id          = "POLICY_ID"        # Replace with your policy ID
#   status             = "ACTIVE"                      # Status of the policy
#   priority           = 1                             # Rule priority
#   network_connection = "ANYWHERE"                    # Network connection: ANYWHERE, ZONE, etc.

#   # Actions
#   password_change = "ALLOW" # Allow users to change their password
#   password_reset  = "DENY"  # Allow users to reset their password
#   password_unlock = "DENY"  # Deny users the ability to unlock their accounts

#   # Optional Exclusions
#   users_excluded = ["OMIT"] # Replace with actual User IDs to exclude (if any)
# }

# # Define Password Policy Rule: Default Rule
# resource "okta_policy_rule_password" "default_password_rule" {
#   name               = "Default Password Policy Rule"
#   policy_id          = "POLICY_ID" # Replace with your policy ID
#   status             = "ACTIVE"               # Status of the policy
#   priority           = 2                      # Rule priority
#   network_connection = "ANYWHERE"             # Network connection: ANYWHERE, ZONE, etc.

#   # Actions
#   password_change = "DENY" # Deny users the ability to change their password
#   password_reset  = "DENY" # Deny users the ability to reset their password
#   password_unlock = "DENY" # Deny users the ability to unlock their accounts

#   # This is a default rule; typically, no users are excluded.
# }
```

### Debug Output

Please see below - Gist will not take the 158K lines

### Panic Output

`The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.`
`The plugin.(*GRPCProvider).ValidateDataResourceConfig request was cancelled.`
`The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.`

```
Stack trace from the terraform-provider-okta_v4.12.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1b43231]

goroutine 105 [running]:
github.com/okta/terraform-provider-okta/okta.syncRuleFromUpstream(0xc0005d0280?, 0xc000930500)
github.com/okta/terraform-provider-okta/okta/policy_rule.go:210 +0xd1
github.com/okta/terraform-provider-okta/okta.resourcePolicyPasswordRuleRead({0x2449620?, 0xc000237490?}, 0x0?, {0x1f65700?, 0xc00057ec60?})
github.com/okta/terraform-provider-okta/okta/resource_okta_policy_rule_password.go:63 +0x194
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003b7a40, {0x2449578, 0xc0002d3e00}, 0xd?, {0x1f65700, 0xc00057ec60})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:795 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003b7a40, {0x2449578, 0xc0002d3e00}, 0xc0007ac750, {0x1f65700, 0xc00057ec60})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00036d068, {0x2449578?, 0xc0000bdf80?}, 0xc00037a0c0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.30.0/helper/schema/grpc_provider.go:661 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x24495b0?, {0x2449578?, 0xc0000bdc20?}, 0xc00037a0c0)
github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0002b80a0, {0x2449578?, 0xc0003773b0?}, 0xc00090a480)
github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:775 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x20b7d40?, 0xc0002b80a0}, {0x2449578, 0xc0003773b0}, 0xc0002c4f80, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c6e00, {0x2449578, 0xc000377320}, {0x244fd38, 0xc0001d8300}, 0xc00002a900, 0xc0004b4c90, 0x33756e8, 0x0)
google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0001c6e00, {0x244fd38, 0xc0001d8300}, 0xc00002a900)
google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 39
google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-okta_v4.12.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior

A Plan should have been generated

#### Can this be done in the Admin UI?

N/A

#### Can this be done in the actual API call?

N/A

### Actual Behavior

Terraform Plugin Crashed

### Steps to Reproduce

Using our Terraform Configuration:
1. Run Plan
2. Terraform Provider Crashes

### Important Factoids

Unfortunately this occurred once, and haven't been able to have it re-occur, even when trying to plan or apply the same code. 

### References

Okta Support Case# 02264245

**Comment by delize** [comment]
I now have an DEBUG output of when the provider crashes, however, the length of the plan, is 158K lines and causes Gist to crash out. I cannot provide the full debug output to gist. 

Happy to provide this file via email or a Google Drive link - as it contains company information. Please let me know how you would like to move forward.
