### ISSUE TITLE
Okta Password policy and mfa policy causing crash

### ISSUE THREAD

**Issue by karlsequeira** [okta/terraform-provider-okta#261]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform  0.13
Okta  3.7.3

### Affected Resource(s)

- resource "okta_policy_password" 

### Terraform Configuration Files

resource "okta_policy_password" "base" {
  name                                   = "Base Password Policy"
  status                                 = "ACTIVE"
  description                            = "Base Password Policy"
  auth_provider                          = "OKTA"
  priority                               = 1
}
resource "okta_policy_password" "site" {
  name                                   = "Sites Password Policy"
  status                                 = "ACTIVE"
  description                            = "Web Sites Password Policy"
  auth_provider                          = "OKTA"
  priority                               = 2
}
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

okta_policy_mfa.site: Modifications complete after 0s [id=00p7rywb5BadqjcZR1d5]

Error: rpc error: code = Unavailable desc = transport is closing

panic: runtime error: invalid memory address or nil pointer dereference
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: [signal 0xc0000005 code=0x0 addr=0x0 pc=0x1d3756f]
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: goroutine 70 [running]:
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/oktadeveloper/terraform-provider-okta/okta.resourcePolicyPasswordRead(0x21b92e0, 0xc00028c4e0, 0xc000710000, 0x1e71ea0, 0xc00055b0e0, 0x0, 0x0, 0x0)
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/oktadeveloper/terraform-provider-okta/okta/resource_okta_policy_password.go:218 +0x58f
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/oktadeveloper/terraform-provider-okta/okta.resourcePolicyPasswordCreate(0x21b92e0, 0xc00028c4e0, 0xc000710000, 0x1e71ea0, 0xc00055b0e0, 0xc000729470, 0x1879a32, 0xc0002dece0)
2020-12-26T07:53:47.130-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/oktadeveloper/terraform-provider-okta/okta/resource_okta_policy_password.go:189 +0x225
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00009c480, 0x21b9260, 0xc00028a440, 0xc000710000, 0x1e71ea0, 0xc00055b0e0, 0x0, 0x0, 0x0)
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/resource.go:285 +0x1f4
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00009c480, 0x21b9260, 0xc00028a440, 0xc00049ab60, 0xc0002dece0, 0x1e71ea0, 0xc00055b0e0, 0x0, 0x0, 0x0, ...)
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/resource.go:396 +0x674
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000287b60, 0x21b9260, 0xc00028a440, 0xc000428190, 0xc00028a440, 0x0, 0x21c8080)
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.0/helper/schema/grpc_provider.go:955 +0x8ef
2020-12-26T07:53:47.131-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000480a80, 0x21b9260, 0xc00028a440, 0xc00049aa10, 0xc000480a80, 0xc000314030, 0xc0002f9ba0)
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:331 +0xb8
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1fa9ee0, 0xc000480a80, 0x21b9320, 0xc000314030, 0xc000416060, 0x0, 0x21b9320, 0xc000314030, 0xc00043ce00, 0x60e)
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000592000, 0x21c5200, 0xc000084480, 0xc0005d8200, 0xc0006827e0, 0x281ae60, 0x0, 0x0, 0x0)
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: google.golang.org/grpc.(*Server).handleStream(0xc000592000, 0x21c5200, 0xc000084480, 0xc0005d8200, 0x0)
2020-12-26T07:53:47.132-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         google.golang.org/grpc@v1.32.0/server.go:1517 +0xd25
2020-12-26T07:53:47.133-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028e1d0, 0xc000592000, 0x21c5200, 0xc000084480, 0xc0005d8200)
2020-12-26T07:53:47.133-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         google.golang.org/grpc@v1.32.0/server.go:859 +0xa8
2020-12-26T07:53:47.133-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-12-26T07:53:47.133-0800 [DEBUG] plugin.terraform-provider-okta_v3.7.3.exe:         google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2020-12-26T07:53:47.145-0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/12/26 07:53:47 [DEBUG] okta_policy_password.site: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/26 07:53:47 [TRACE] EvalMaybeTainted: okta_policy_password.site encountered an error during creation, so it is now marked as tainted
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalWriteState
2020/12/26 07:53:47 [TRACE] EvalWriteState: removing state object for okta_policy_password.site
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalApplyProvisioners
2020/12/26 07:53:47 [TRACE] EvalApplyProvisioners: okta_policy_password.site has no state, so skipping provisioners
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalMaybeTainted
2020/12/26 07:53:47 [TRACE] EvalMaybeTainted: okta_policy_password.site encountered an error during creation, so it is now marked as tainted
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalWriteState
2020/12/26 07:53:47 [TRACE] EvalWriteState: removing state object for okta_policy_password.site
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalIf
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalIf
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalWriteDiff
2020/12/26 07:53:47 [TRACE] eval: *terraform.EvalApplyPost
2020/12/26 07:53:47 [ERROR] eval: *terraform.EvalApplyPost, err: rpc error: code = Unavailable desc = transport is closing
2020/12/26 07:53:47 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/12/26 07:53:47 [TRACE] [walkApply] Exiting eval tree: okta_policy_password.site
2020/12/26 07:53:47 [TRACE] vertex "okta_policy_password.site": visit complete
2020/12/26 07:53:47 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/oktadeveloper/okta\"] (close)" errored, so skipping
2020/12/26 07:53:47 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/12/26 07:53:47 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/12/26 07:53:47 [DEBUG] Uploading remote state to S3: {
  Body: buffer(0xc0009ac780),
  Bucket: "XXXXXX",
  ContentLength: 7992,
  ContentType: "application/json",
  Key: "okta-admin-base.tfstate"
}
2020-12-26T07:53:47.172-0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/oktadeveloper/okta/3.7.3/windows_amd64/terraform-provider-okta_v3.7.3.exe pid=28112 error="exit status 2"
2020-12-26T07:53:47.409-0800 [DEBUG] plugin: plugin exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
### Steps to Reproduce

1. Configure a new Tenant. 
2. `terraform init`
3. `terraform apply`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi @karlsequeira! Thanks for submitting this issue! I think the problem is in the `password_dictionary_lookup` field, which is in `beta`, so I assume it's not yet present in all organisations. I will add a `nil` check to avoid panic in the provider and will release bugfix in v3.7.4 shortly!
