### ISSUE TITLE
Importing Okta Workflows OIDC application segfaults

### ISSUE THREAD

**Issue by tomaspinho** [okta/terraform-provider-okta#404]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- okta_app_oauth

### Terraform Configuration Files

```hcl
resource "okta_app_oauth" "okta_workflows" {
  label = "Okta Workflows"

  type = "web"
}
```

### Debug Output

The application doesn't have a `Credentials.OAuthClient` as it's not returned by the Okta API:

```
{
 "id": "[id]",
 "name": "okta_flow_sso",
 "label": "Okta Workflows",
 "status": "ACTIVE",
 "lastUpdated": "2021-02-10T13:08:40.000Z",
 "created": "2021-02-10T13:08:40.000Z",
 "accessibility": {
  "selfService": false,
  "errorRedirectUrl": null,
  "loginRedirectUrl": null
 },
 "visibility": {
  "autoSubmitToolbar": false,
  "hide": {
   "iOS": false,
   "web": false
  },
  "appLinks": {}
 },
 "features": [],
 "signOnMode": "OPENID_CONNECT",
 "credentials": {
  "userNameTemplate": {
   "template": "${source.login}",
   "type": "BUILT_IN"
  },
  "signing": {
   "kid": ""
  }
 },
 "settings": {
  "app": {
   "redirectURI": "https://[us].workflows.okta.com/oidc/[id]/cb",
   "initiateLoginURI": "https://[us].workflows.okta.com/oidc/[id]/login"
  },
  "notifications": {
   "vpn": {
    "network": {
     "connection": "DISABLED"
    },
    "message": null,
    "helpUrl": null
   }
  }
 },
 "_links": {
  "appLinks": [],
  "groups": {
   "href": "https://[us].okta.com/api/v1/apps/[id]/groups"
  },
  "logo": [
   {
    "name": "medium",
    "href": "https://ok12static.oktacdn.com/assets/img/logos/okta-workflows.27df74eb53570679e5cc3a4b0f160602.png",
    "type": "image/png"
   }
  ],
  "users": {
   "href": "https://[us].okta.com/api/v1/apps/[id]/users"
  },
  "deactivate": {
   "href": "https://[us].okta.com/api/v1/apps/[id]/lifecycle/deactivate"
  }
 }
}

```

### Panic Output

```
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf2016c]
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: goroutine 39 [running]:
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: github.com/oktadeveloper/terraform-provider-okta/okta.resourceAppOAuthRead(0x13efe20, 0xc0009c7140, 0xc000313680, 0x10a1f20, 0xc0001bcf00, 0xc000503ef0, 0xc0005658f0, 0x40e0f8)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	github.com/oktadeveloper/terraform-provider-okta/okta/resource_okta_app_oauth.go:360 +0x30c
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000376b40, 0x13efda0, 0xc00099a940, 0xc000313680, 0x10a1f20, 0xc0001bcf00, 0x0, 0x0, 0x0)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:297 +0x1ea
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000376b40, 0x13efda0, 0xc00099a940, 0xc0000f62a0, 0x10a1f20, 0xc0001bcf00, 0xc00013f020, 0x0, 0x0, 0x0)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/resource.go:564 +0x1cb
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000cb40, 0x13efda0, 0xc00099a940, 0xc00099ad80, 0xc00099a940, 0x118a7a0, 0x11d94e0)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.3/helper/schema/grpc_provider.go:575 +0x43b
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000305ec0, 0x13efda0, 0xc00099a940, 0xc0009c6cc0, 0xc000305ec0, 0xc0002b7290, 0xc000926ba0)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x11d94e0, 0xc000305ec0, 0x13efe60, 0xc0002b7290, 0xc0009c6c60, 0x0, 0x13efe60, 0xc0002b7290, 0xc0000de6c0, 0x204)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000375500, 0x13fb440, 0xc00042be00, 0xc00055e100, 0xc0001c6600, 0x1a5c0b0, 0x0, 0x0, 0x0)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x522
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: google.golang.org/grpc.(*Server).handleStream(0xc000375500, 0x13fb440, 0xc00042be00, 0xc00055e100, 0x0)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd05
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00012a480, 0xc000375500, 0x13fb440, 0xc00042be00, 0xc00055e100)
2021-03-29T16:01:56.802+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xa5
2021-03-29T16:01:56.803+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-29T16:01:56.803+0100 [DEBUG] plugin.terraform-provider-okta_v3.10.0: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
2021-03-29T16:01:56.804+0100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/oktadeveloper/okta/3.10.0/linux_amd64/terraform-provider-okta_v3.10.0 pid=74516 error="exit status 2"

```

### Expected Behavior

The resource should have been imported.

### Actual Behavior

Segfault as above.

### Steps to Reproduce

1. `terraform import okta_app_oauth.okta_workflows [id]`

### References

- #0000

**Comment by bogdanprodan-okta** [comment]
Hi, @tomaspinho! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by tomaspinho** [comment]
Please re-open
