### ISSUE TITLE
Issue with okta_users data source 

### ISSUE THREAD

**Issue by asheynkmantyler** [okta/terraform-provider-okta#549]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.0.0
on darwin_amd64

### Affected Resource(s)
data.okta_users

- okta_xxx

### Terraform Configuration Files

main.tf:
```hcl
terraform {
  required_providers {
    
    okta = {
      source = "okta/okta"
      version = ">=3.12"
    }
  }
}

provider "okta" {
	org_name = "tylertech"
}

resource "null_resource" "test" {
  triggers = {
    "always_run" = timestamp()
  }
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "exit 0"
  }
}

module "ooo" {
	depends_on = [
	  null_resource.test
	]
	source = "./user_management"
	
}

output "mmm" {
  value = module.ooo.out
```

module file:
```hcl
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = ">=3.12"
    }
  }
}

data "okta_users" "privx_user_list" {
  search {
    name = "profile.login"
    value = "albert.sheynkman@tylertech.com"
    comparison = "eq"
  }
}

locals {
  yyy = data.okta_users.privx_user_list
  okta_user_map = local.yyy["users"]

}
output "out" {
  value = {
    "okta_user_map" : local.okta_user_map
    "length" : length(data.okta_users.privx_user_list.users)
    
  }
}

```
### Expected Behavior

Since user albert.sheynkman@tylertech.com exists, I would expect length of the output to be 1 and okta_user_map output to contain data result
This works fine, if I comment out "depends_on" stanza in main.tf file - I get length to be 1.

### Actual Behavior

If depends_on stanza is present, it length output is 0 and okta_user_map output is empty list.

### Steps to Reproduce

comment out "depends_on" stanza and run the plan. You will see that it works fine.
then remove comments (enable depends_on). length would be 0 and okta_user_map would be empty

1. `terraform apply`

### References

- #0000

**Comment by asheynkmantyler** [comment]
I did some more testing of this behavior, and I found that "errored" behavior is only produced when resources in depends_on section need to be created. So the following code:
```hcl
terraform {
  required_providers {
    
    okta = {
      source = "okta/okta"
      version = ">=3.12"
    }
  }
}

provider "okta" {
	org_name = "tylertech"
}

resource "null_resource" "test" {
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    command     = "exit 0"
  }
}

module "ooo" {
	depends_on = [
	  null_resource.test
	]
	source = "./user_management"
	
}

output "mmm" {
  value = module.ooo.out
}
```
will error out first time it is being run, but will be good all subsequent times.

**Comment by bogdanprodan-okta** [comment]
Hi @asheynkmantyler! Thanks for submitting this issue! I'll try to reproduce the problem and get back to you asap. Cheers!

**Comment by bogdanprodan-okta** [comment]
Hi @asheynkmantyler! Thanks for submitting this issue! I'll try to reproduce the problem and get back to you asap. Cheers!

**Comment by asheynkmantyler** [comment]
Hi @bogdanprodan-okta ! did you get a chance to recreate this issue? Thanks

**Comment by abatilo** [comment]
I believe I'm having the same issue:

```
Error: Plugin did not respond

  with data.okta_user.spinnaker,
  on main.tf line 9, in data "okta_user" "spinnaker":
   9: data "okta_user" "spinnaker" {

The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more
details.

Stack trace from the terraform-provider-okta_v3.13.3 plugin:

panic: the API returned an error: You do not have permission to perform the requested action

goroutine 43 [running]:
github.com/okta/terraform-provider-okta/okta/internal/transport.(*AuthTransport).RoundTrip(0xc000265430, 0xc0002a6900, 0xc000265430, 0x0, 0x0)
	github.com/okta/terraform-provider-okta/okta/internal/transport/auth.go:40 +0x190
net/http.send(0xc0002a6900, 0xfdaa40, 0xc000265430, 0x0, 0x0, 0x0, 0xc00012ee30, 0x4b1c0b, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc00007a690, 0xc0002a6900, 0x0, 0x0, 0x0, 0xc00012ee30, 0x0, 0x1, 0xc000668da4)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc00007a690, 0xc0002a6900, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000150310, 0xc000719a20, 0x0, 0x0, 0x0)
	github.com/hashicorp/go-retryablehttp@v0.7.0/client.go:591 +0x16e
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc00043ec30, 0xc0002a6900, 0xc00043ec30, 0x0, 0x0)
	github.com/hashicorp/go-retryablehttp@v0.7.0/roundtripper.go:44 +0x85
net/http.send(0xc0002a6900, 0xfd9980, 0xc00043ec30, 0x0, 0x0, 0x0, 0xc00012ee20, 0xc00067d2b0, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc00007a6c0, 0xc0002a6900, 0x0, 0x0, 0x0, 0xc00012ee20, 0x0, 0x1, 0x48)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc00007a6c0, 0xc0002a6900, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/okta/okta-sdk-golang/v2/okta.(*RequestExecutor).doWithRetries.func2(0xc00065ea50, 0xc00065ea50)
	github.com/okta/okta-sdk-golang/v2@v2.5.2/okta/requestExecutor.go:329 +0x152
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc00067d1d0, 0xfe4b38, 0xc00065ea50, 0x0, 0xfe9fd8, 0xc00012ee10, 0x0, 0x0)
	github.com/cenkalti/backoff/v4@v4.1.1/retry.go:55 +0x102
github.com/cenkalti/backoff/v4.RetryNotify(...)
	github.com/cenkalti/backoff/v4@v4.1.1/retry.go:34
github.com/cenkalti/backoff/v4.Retry(...)
	github.com/cenkalti/backoff/v4@v4.1.1/retry.go:28
github.com/okta/okta-sdk-golang/v2/okta.(*RequestExecutor).doWithRetries(0xc000130a20, 0xfee288, 0xc00028e5a0, 0xc0002a6300, 0x3, 0xc00071a308, 0xe)
	github.com/okta/okta-sdk-golang/v2@v2.5.2/okta/requestExecutor.go:356 +0x1ac
github.com/okta/okta-sdk-golang/v2/okta.(*RequestExecutor).Do(0xc000130a20, 0xfee288, 0xc00028e5a0, 0xc0002a6300, 0xd3ae60, 0xc000660708, 0x0, 0xc0002a6300, 0x0)
	github.com/okta/okta-sdk-golang/v2@v2.5.2/okta/requestExecutor.go:264 +0x1be
github.com/okta/okta-sdk-golang/v2/okta.(*UserResource).ListAssignedRolesForUser(0xc0001b6490, 0xfee288, 0xc00028e5a0, 0xc0000383a8, 0x14, 0x0, 0x1, 0xd6ec00, 0xc000719330, 0xc0003a0640, ...)
	github.com/okta/okta-sdk-golang/v2@v2.5.2/okta/user.go:792 +0x1d2
github.com/okta/terraform-provider-okta/okta.listUserOnlyRoles(0xfee288, 0xc00028e5a0, 0xc0001b6480, 0xc0000383a8, 0x14, 0x0, 0xc00000c6f8, 0xf03588, 0xc00067d4d8, 0x1c2, ...)
	github.com/okta/terraform-provider-okta/okta/user.go:253 +0x85
github.com/okta/terraform-provider-okta/okta.setAdminRoles(0xfee288, 0xc00028e5a0, 0xc0002aa900, 0xd990a0, 0xc00092ec30, 0x1, 0x4)
	github.com/okta/terraform-provider-okta/okta/user.go:271 +0xd6
github.com/okta/terraform-provider-okta/okta.dataSourceUserRead(0xfee288, 0xc00028e5a0, 0xc0002aa900, 0xd990a0, 0xc00092ec30, 0xc000862f00, 0xc000755948, 0x40e0f8)
	github.com/okta/terraform-provider-okta/okta/data_source_okta_user.go:81 +0x4d7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000457960, 0xfee218, 0xc0002e81c0, 0xc0002aa900, 0xd990a0, 0xc00092ec30, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000457960, 0xfee218, 0xc0002e81c0, 0xc00013cd00, 0xd990a0, 0xc00092ec30, 0xc00092ec30, 0xc00013cd00, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:558 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00043e9a8, 0xfee218, 0xc0002e81c0, 0xc00013c6a0, 0xc0002e81c0, 0x40b965, 0xe3fe40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:1105 +0x4d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc0004cfc80, 0xfee2c0, 0xc0002e81c0, 0xc000828140, 0xc0004cfc80, 0xc0000a6390, 0xc000846ba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0xe75460, 0xc0004cfc80, 0xfee2c0, 0xc0000a6390, 0xc00028e1e0, 0x0, 0xfee2c0, 0xc0000a6390, 0xc000840240, 0x229)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002c6540, 0xff6858, 0xc00008aa80, 0xc0002a6500, 0xc0000a6a20, 0x14ce810, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002c6540, 0xff6858, 0xc00008aa80, 0xc0002a6500, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000116480, 0xc0002c6540, 0xff6858, 0xc00008aa80, 0xc0002a6500)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-okta_v3.13.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

I get the following panic stack trace when all I'm doing is:
```
data "okta_user" "spinnaker" {
  search {
    name  = "profile.login"
    value = "my_email_address"
  }
}
```

**Comment by bogdanprodan-okta** [comment]
Hi @abatilo @asheynkmantyler! Are you still able to reproduce this issue using the latest provider's version?

**Comment by bogdanprodan-okta** [comment]
I'm closing this issue for now, but if it still exists in the latest version, please leave a comment.
