### ISSUE TITLE
Invalid Memory Address Segfault on 3.18.0

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#793]
`Terraform 1.0.10`
`okta/okta 3.18.0`

```
Stack trace from the terraform-provider-okta_v3.18.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xef0779]

goroutine 775 [running]:
github.com/okta/terraform-provider-okta/okta.doesResourceExist(...)
        github.com/okta/terraform-provider-okta/okta/utils.go:245
github.com/okta/terraform-provider-okta/okta.checkIfGroupHasUsers({0x123ab68, 0xc0008b1a40}, 0xc0003b9180, {0xc00031af18, 0x14}, {0x0, 0x0, 0x0})
        github.com/okta/terraform-provider-okta/okta/resource_okta_group_memberships.go:123 +0xb9
github.com/okta/terraform-provider-okta/okta.resourceGroupMembershipsRead({0x123ab68, 0xc0008b1a40}, 0x1733c5e0eb8, {0xfec240, 0xc00024f860})
        github.com/okta/terraform-provider-okta/okta/resource_okta_group_memberships.go:72 +0xf5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003ecfc0, {0x123aaf8, 0xc0003b9180}, 0x24, {0xfec240, 0xc00024f860})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:347 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003ecfc0, {0x123aaf8, 0xc0003b9180}, 0xc0004b12b0, {0xfec240, 0xc00024f860})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00042ade0, {0x123aaf8, 0xc0003b9180}, 0xc0003b91c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000498ba0, {0x123aba0, 0xc0006b0960}, 0xc0008b16e0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10b8800, 0xc000498ba0}, {0x123aba0, 0xc0006b0960}, 0xc0008b1680, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a8a80, {0x124a8f0, 0xc0001ac180}, 0xc0008be000, 0xc00049b0e0, 0x17b6c10, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002a8a80, {0x124a8f0, 0xc0001ac180}, 0xc0008be000, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-okta_v3.18.0.exe plugin crashed!
```

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll fix this issue and make a release today.

**Comment by virgofx** [comment]
Confirm fixed, thanks @bogdanprodan-okta
