### ISSUE TITLE
Segmentation Fault while importing facebook IDP

### ISSUE THREAD

**Issue by BillRamsey-minted** [okta/terraform-provider-okta#809]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/okta/okta v3.19.0
```

### Affected Resource(s)

- okta_idp_oidc

### Terraform Configuration Files

```hcl
resource "okta_idp_oidc" "facebook_dev" {
  name                  = "example"
  authorization_url     = "https://idp.example.com/authorize"
  authorization_binding = "HTTP-REDIRECT"
  token_url             = "https://idp.example.com/token"
  token_binding         = "HTTP-POST"
  user_info_url         = "https://idp.example.com/userinfo"
  user_info_binding     = "HTTP-REDIRECT"
  jwks_url              = "https://idp.example.com/keys"
  jwks_binding          = "HTTP-REDIRECT"
  scopes                = ["openid"]
  client_id             = ""
  client_secret         = ""
  issuer_url            = "https://id.example.com"
  username_template     = "idpuser.email"
}
```

### Panic Output

```
% terraform import okta_idp_oidc.facebook_dev 0oaysbgemaXXXXXXXXXX

okta_idp_oidc.facebook_dev: Importing from ID "0oaysbgemaXXXXXXXXXX"...
okta_idp_oidc.facebook_dev: Import prepared!
  Prepared okta_idp_oidc for import
okta_idp_oidc.facebook_dev: Refreshing state... [id=0oaysbgemaXXXXXXXXXX]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-okta_v3.19.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x17812b9]

goroutine 97 [running]:
github.com/okta/terraform-provider-okta/okta.resourceIdpRead({0x1acb348, 0xc000203200}, 0xc0000f6d80, {0x1879ee0, 0xc00035cd00})
	github.com/okta/terraform-provider-okta/okta/resource_okta_idp_oidc.go:110 +0x459
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004576c0, {0x1acb2d8, 0xc00010c9c0}, 0x24, {0x1879ee0, 0xc00035cd00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:347 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004576c0, {0x1acb2d8, 0xc00010c9c0}, 0xc000406820, {0x1879ee0, 0xc00035cd00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:624 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00048edc8, {0x1acb2d8, 0xc00010c9c0}, 0xc00010ca00)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0004f2a60, {0x1acb380, 0xc00052e450}, 0xc000202de0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1948ea0, 0xc0004f2a60}, {0x1acb380, 0xc00052e450}, 0xc000202d80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000124a80, {0x1adab90, 0xc00061c000}, 0xc00031a6c0, 0xc0004f5110, 0x2050f70, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000124a80, {0x1adab90, 0xc00061c000}, 0xc00031a6c0, 0x0)
	google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-okta_v3.19.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behavior

Imported the info out of okta into state

### Actual Behavior

crash

### Steps to Reproduce

1. `terraform import okta_idp_oidc.facebook_dev 0oaysbgemaXXXXXXXXXX`

### Important Factoids

Note, other IDPs import correctly

### References

Thank you!

**Comment by BillRamsey-minted** [comment]
Should have imported with okta_idp_social.

```
terraform import okta_idp_social.facebook_dev
```
works.  Thank you.
