### ISSUE TITLE
Okta Policy MFA SegFault

### ISSUE THREAD

**Issue by virgofx** [okta/terraform-provider-okta#879]
This happens when using `okta_policy_mfa` and `okta_policy_rule_mfa` rules with OIE enabled on tenant. Then making changes in the UI and simply re-planning/re-applying will result in these errors continuously:

```
Stack trace from the terraform-provider-okta_v3.20.2.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1339228]

goroutine 208 [running]:
github.com/okta/terraform-provider-okta/okta.resourcePolicyMfaRead({0x167d9e8, 0xc000832600}, 0x1143b5c0108, {0x1423320, 0xc00043cd00})
        github.com/okta/terraform-provider-okta/okta/resource_okta_policy_mfa.go:44 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0004d81c0, {0x167d978, 0xc00058f240}, 0x24, {0x1423320, 0xc00043cd00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0004d81c0, {0x167d978, 0xc00058f240}, 0xc00004d450, {0x1423320, 0xc00043cd00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0004f0e88, {0x167d978, 0xc00058f240}, 0xc00058f280)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00009ed00, {0x167da20, 0xc00012c3c0}, 0xc000341bc0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:298 +0x1fb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x14f4440, 0xc00009ed00}, {0x167da20, 0xc00012c3c0}, 0xc000341b60, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002b2700, {0x168dc70, 0xc0001b4480}, 0xc000692b40, 0xc0001db9b0, 0x1c10eb0, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002b2700, {0x168dc70, 0xc0001b4480}, 0xc000692b40, 0x0)
        google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-okta_v3.20.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/okta/okta v3.20.2
````

**Comment by bogdanprodan-okta** [comment]
Hi, @virgofx! Thanks for submitting this issue! I'll investigate the problem and get back to you asap.

**Comment by virgofx** [comment]
@bogdanprodan-okta Any insight into what's happening with this one?

**Comment by rc-ssoltau** [comment]
Also experiencing this issue, we are set to go-live with Okta today and this issue has completely broken our workspace, even when commenting out the resources related to the factors/policies. 

If there are any workarounds or an ability to get this resolved today, that would be greatly appreciated. Thanks!
